import csv
import urllib.request
import io
import sys

CSV_URL = "https://raw.githubusercontent.com/datasets/airport-codes/main/data/airport-codes.csv"
OUTPUT_PATH = "Shared/Resources/AirportCodesData.swift"

def process_airports():
    print(f"Downloading CSV from {CSV_URL}...")
    try:
        with urllib.request.urlopen(CSV_URL) as response:
            csv_content = response.read().decode('utf-8')
    except Exception as e:
        print(f"Error downloading CSV: {e}")
        return

    print("Download complete. Parsing CSV...")

    csv_file = io.StringIO(csv_content)
    reader = csv.DictReader(csv_file)

    # Store simplified lines
    lines = []
    count = 0
    skipped = 0

    for row in reader:
        iata = row.get("iata_code", "").strip().upper()
        coordinates = row.get("coordinates", "").strip()
        country = row.get("iso_country", "").strip()

        if len(iata) != 3 or not iata.isalnum() or not coordinates:
            skipped += 1
            continue

        try:
            parts = coordinates.split(",")
            if len(parts) != 2:
                skipped += 1
                continue

            lat = parts[0].strip() # Keep as string to avoid float precision issues during transfer
            lon = parts[1].strip()

            # CSV Format: IATA,LAT,LON,COUNTRY
            lines.append(f"{iata},{lat},{lon},{country}")
            count += 1

        except ValueError:
            skipped += 1
            continue

    print(f"Processed {count} airports (skipped {skipped}). Generating Swift file...")

    swift_content = """//
//  AirportCodesData.swift
//  Learn
//
//  Generated by tasks/process_airports.py
//

import Foundation

let airportCodesCSV = \"\"\"
"""

    swift_content += "\n".join(lines)
    swift_content += "\n\"\"\"\n"

    with open(OUTPUT_PATH, "w") as f:
        f.write(swift_content)

    print(f"Done. Saved to {OUTPUT_PATH}")

if __name__ == "__main__":
    process_airports()
